spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
    connection-timeout: 5s
    socket-timeout: 10s

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: auction-read-cdc




management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
server:
  port: 8080