spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
    connection-timeout: 30s
    socket-timeout: 10s
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: auction-read-cdc




management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /search-service/v3/api-docs/swagger-config
    url: /search-service/v3/api-docs

server:
  port: 8080